# Generated by Django 3.2.7 on 2021-11-11 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_bisnis', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=250)),
                ('update_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cabang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_cabang', models.CharField(max_length=10)),
                ('tipe_cabang', models.CharField(max_length=10)),
                ('nama_cabang', models.CharField(max_length=250)),
                ('segmentasi', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('update_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_coa', models.CharField(max_length=30)),
                ('nama', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('update_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KategoriKejadian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_kategori', models.CharField(max_length=10)),
                ('nama_kategori', models.CharField(max_length=250)),
                ('update_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KategoriLaporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.TextField()),
                ('periode_awal', models.DateField()),
                ('periode_akhir', models.DateField()),
                ('creator', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='led.kategorilaporan')),
            ],
        ),
        migrations.CreateModel(
            name='Led',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_kasus', models.CharField(max_length=50)),
                ('tanggal_kejadian', models.DateField(blank=True, default=None, null=True)),
                ('tanggal_teridentifikasi', models.DateField(blank=True, default=None, null=True)),
                ('tanggal_input', models.DateField(blank=True, default=None, null=True)),
                ('tanggal_selesai', models.DateField(blank=True, default=None, null=True)),
                ('tanggal_update', models.DateTimeField(blank=True, default=None, null=True)),
                ('jumlah_kasus', models.IntegerField()),
                ('nama_pembuat', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('nama_penemu', models.CharField(max_length=100)),
                ('mata_uang', models.CharField(max_length=10)),
                ('nilai_tukar', models.IntegerField()),
                ('kerugian_potensial', models.BigIntegerField()),
                ('rra', models.BigIntegerField()),
                ('recovery', models.BigIntegerField()),
                ('kerugian_aktual', models.BigIntegerField()),
                ('tanggal_review', models.DateField()),
                ('reviewer', models.CharField(max_length=20)),
                ('hasil_review', models.TextField()),
                ('keterangan_review', models.TextField()),
                ('summary_kejadian', models.TextField()),
                ('kronologi_kejadian', models.TextField()),
                ('tindakan_unit_kerja', models.TextField()),
                ('tindakan_perbaikan', models.TextField()),
                ('dibuat_oleh', models.CharField(max_length=100)),
                ('disetujui_oleh', models.CharField(max_length=100)),
                ('risiko_kredit', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bussines_line', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='led.businessline')),
                ('coa_biaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='led.coa')),
                ('kode_cabang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='led.cabang')),
                ('kode_ktg_kejadian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='led.kategorikejadian')),
            ],
        ),
        migrations.CreateModel(
            name='Penyebab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_penyebab', models.CharField(max_length=15)),
                ('nama_penyebab', models.CharField(max_length=250)),
                ('update_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_produk', models.CharField(max_length=10)),
                ('tipe_produk', models.CharField(max_length=50)),
                ('nama_produk', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=250)),
                ('update_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_unit', models.CharField(max_length=10)),
                ('nama_unit', models.CharField(max_length=250)),
                ('update_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StateChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kolom', models.CharField(max_length=50)),
                ('value', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nomor_kasus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomorKasus', to='led.led')),
                ('nomor_kasus2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomorKasus2', to='led.led')),
            ],
        ),
        migrations.CreateModel(
            name='LedLaporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='led.laporan')),
                ('led_laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='led.led')),
            ],
        ),
        migrations.AddField(
            model_name='led',
            name='kode_penyebab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='led.penyebab'),
        ),
        migrations.AddField(
            model_name='led',
            name='kode_produk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='led.produk'),
        ),
    ]
