# Generated by Django 3.2.7 on 2021-12-01 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('led', '0002_auto_20211123_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perubahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kolom', models.TextField(blank=True, null=True)),
                ('data_lama', models.TextField(blank=True, null=True)),
                ('data_baru', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('alasan', models.TextField(blank=True, null=True)),
                ('reviewer', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nomor_kasus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='led.led')),
            ],
        ),
    ]
