# Generated by Django 3.2.7 on 2021-12-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('led', '0003_perubahan'),
    ]

    operations = [
        migrations.AddField(
            model_name='led',
            name='ditemukan_oleh',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
