# Generated by Django 3.2.7 on 2021-12-02 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('led', '0004_led_ditemukan_oleh'),
    ]

    operations = [
        migrations.AddField(
            model_name='perubahan',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
