# Generated by Django 3.2.7 on 2021-12-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('led', '0005_perubahan_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategorikejadian',
            name='kode_kategori',
        ),
        migrations.RemoveField(
            model_name='kategorikejadian',
            name='nama_kategori',
        ),
        migrations.RemoveField(
            model_name='penyebab',
            name='kode_penyebab',
        ),
        migrations.RemoveField(
            model_name='penyebab',
            name='nama_penyebab',
        ),
        migrations.AddField(
            model_name='kategorikejadian',
            name='kode_kategori1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kategorikejadian',
            name='kode_kategori2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kategorikejadian',
            name='kode_kategori3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kategorikejadian',
            name='nama_kategori1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kategorikejadian',
            name='nama_kategori2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kategorikejadian',
            name='nama_kategori3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kategorikejadian',
            name='status',
            field=models.BooleanField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='penyebab',
            name='kode_penyebab1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='penyebab',
            name='kode_penyebab2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='penyebab',
            name='kode_penyebab3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='penyebab',
            name='nama_penyebab1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='penyebab',
            name='nama_penyebab2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='penyebab',
            name='nama_penyebab3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='penyebab',
            name='status',
            field=models.BooleanField(blank=True, default=1, null=True),
        ),
    ]
