# Generated by Django 3.2.7 on 2021-12-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('led', '0006_auto_20211220_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessline',
            name='update_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cabang',
            name='update_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coa',
            name='update_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kategorikejadian',
            name='update_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='led',
            name='kerugian_aktual',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='led',
            name='kerugian_potensial',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='led',
            name='nilai_tukar',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='led',
            name='recovery',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='led',
            name='rra',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='penyebab',
            name='update_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='update_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
