# Generated by Django 3.2.7 on 2021-12-21 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('led', '0008_auto_20211221_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='led',
            name='bussines_line',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='led.businessline'),
        ),
        migrations.AlterField(
            model_name='led',
            name='coa_biaya',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='led.coa'),
        ),
        migrations.AlterField(
            model_name='led',
            name='kode_cabang',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='led.cabang'),
        ),
        migrations.AlterField(
            model_name='led',
            name='kode_ktg_kejadian',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='led.kategorikejadian'),
        ),
        migrations.AlterField(
            model_name='led',
            name='kode_penyebab',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='led.penyebab'),
        ),
        migrations.AlterField(
            model_name='led',
            name='kode_produk',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='led.produk'),
        ),
        migrations.AlterField(
            model_name='led',
            name='mata_uang',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='led',
            name='nama_pembuat',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='led',
            name='nama_penemu',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='led',
            name='status',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
