# Generated by Django 3.2.7 on 2021-12-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('led', '0009_auto_20211221_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='led',
            name='dihapus',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
