# Generated by Django 3.2.7 on 2022-01-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('led', '0010_led_dihapus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='led',
            name='dihapus',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
