# Generated by Django 3.2.7 on 2022-01-20 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('led', '0011_alter_led_dihapus'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan',
            name='ks_belumrv',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='laporan',
            name='ks_save',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='laporan',
            name='ks_submit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='led',
            name='perlu_email',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='led',
            name='review_user',
            field=models.CharField(blank=True, default='Belum Review', max_length=100, null=True),
        ),
    ]
