# Generated by Django 3.2.7 on 2022-01-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('led', '0012_auto_20220120_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryKejadian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.TextField()),
                ('nama_lv1', models.DateTimeField(auto_now_add=True)),
                ('summ_ormis', models.TextField(blank=True, default=None, null=True)),
                ('summ_ormc', models.TextField(blank=True, default=None, null=True)),
                ('catatan', models.TextField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
