# Generated by Django 3.2.7 on 2022-01-24 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('led', '0013_summarykejadian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='led',
            name='bussines_line',
        ),
    ]
