# Generated by Django 3.2.7 on 2022-01-24 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('led', '0014_remove_led_bussines_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='led',
            name='business_line',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='led.businessline'),
        ),
    ]
