# Generated by Django 3.2.7 on 2022-01-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('led', '0015_led_business_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_kasus', models.TextField()),
                ('tanggal_jurnal', models.DateTimeField(blank=True, null=True)),
                ('debet_kredit', models.TextField(blank=True, default=None, null=True)),
                ('kode_mata_uang', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('jumlah_nominal_asal', models.FloatField(blank=True, default=None, null=True)),
                ('jumlah_nominal_idr', models.FloatField(blank=True, default=None, null=True)),
                ('keterangan', models.TextField(blank=True, default=None, null=True)),
                ('kode_coa', models.TextField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
