# Generated by Django 3.2.7 on 2022-01-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('led', '0017_auto_20220124_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='update_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
