# Generated by Django 3.2.7 on 2022-02-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('led', '0019_auto_20220131_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='led',
            name='kode_ktg_kejadian3',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
