# Generated by Django 3.2.7 on 2022-02-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('led', '0020_led_kode_ktg_kejadian3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kasus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_kasus', models.CharField(max_length=255)),
                ('tanggal_kejadian', models.DateField(blank=True, default=None, null=True)),
                ('tanggal_teridentifikasi', models.DateField(blank=True, default=None, null=True)),
                ('tanggal_input', models.DateField(blank=True, default=None, null=True)),
                ('tanggal_selesai', models.DateField(blank=True, default=None, null=True)),
                ('tanggal_update', models.DateTimeField(blank=True, default=None, null=True)),
                ('jumlah_kasus', models.IntegerField(blank=True, default=None, null=True)),
                ('nama_pembuat', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('status', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('kode_cabang', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('kode_unit', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('tipe_led', models.TextField(blank=True, null=True)),
                ('kode_produk', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('nama_penemu', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('kode_ktg_kejadian', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('kode_penyebab', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('business_line', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('coa_biaya', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('mata_uang', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('nilai_tukar', models.FloatField(blank=True, default=None, null=True)),
                ('kerugian_potensial', models.FloatField(blank=True, default=None, null=True)),
                ('rra', models.FloatField(blank=True, default=None, null=True)),
                ('recovery', models.FloatField(blank=True, default=None, null=True)),
                ('kerugian_aktual', models.FloatField(blank=True, default=None, null=True)),
                ('tanggal_review', models.DateField(blank=True, default=None, null=True)),
                ('reviewer', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('hasil_review', models.TextField(blank=True, default=None, null=True)),
                ('keterangan_review', models.TextField(blank=True, default=None, null=True)),
                ('summary_kejadian', models.TextField(blank=True, default=None, null=True)),
                ('kronologi_kejadian', models.TextField(blank=True, default=None, null=True)),
                ('tindakan_unit_kerja', models.TextField(blank=True, default=None, null=True)),
                ('tindakan_perbaikan', models.TextField(blank=True, default=None, null=True)),
                ('dibuat_oleh', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('ditemukan_oleh', models.CharField(blank=True, max_length=255, null=True)),
                ('disetujui_oleh', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('dihapus', models.BooleanField(blank=True, default=False, null=True)),
                ('chk_kknled', models.BooleanField(blank=True, default=False, null=True)),
                ('chk_summ', models.BooleanField(blank=True, default=False, null=True)),
                ('risiko_kredit', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('review_user', models.CharField(blank=True, default='Belum Review', max_length=100, null=True)),
                ('perlu_email', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='led',
            name='kode_ktg_kejadian3',
        ),
    ]
