# Generated by Django 3.2.7 on 2022-02-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('led', '0021_auto_20220202_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kasus',
            old_name='kode_produk',
            new_name='nama_produk',
        ),
        migrations.AddField(
            model_name='kasus',
            name='nama_cabang',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='kasus',
            name='nama_unit',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
