# Generated by Django 3.2.7 on 2022-02-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('led', '0022_auto_20220204_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='KasusLaporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laporan_id', models.BigIntegerField(blank=True, default=0, null=True)),
                ('kasus_id', models.BigIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
