# Generated by Django 3.2.7 on 2022-01-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LedHistoris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_kasus', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('tanggal_kejadian', models.DateField(blank=True, default=None, null=True)),
                ('tanggal_teridentifikasi', models.DateField(blank=True, default=None, null=True)),
                ('tanggal_input', models.DateField(blank=True, default=None, null=True)),
                ('tanggal_selesai', models.DateField(blank=True, default=None, null=True)),
                ('tanggal_update', models.DateTimeField(blank=True, default=None, null=True)),
                ('jumlah_kasus', models.IntegerField(blank=True, default=None, null=True)),
                ('nama_pembuat', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('status', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('kode_cabang', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('nama_cabang', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('kode_unit', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('nama_unit', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('tipe_led', models.TextField(blank=True, null=True)),
                ('kode_produk', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('nama_produk', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('nama_produk2', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('nama_penemu', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('kode_ktg_kejadian1', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('nama_ktg_kejadian1', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('kode_ktg_kejadian2', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('nama_ktg_kejadian2', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('kode_ktg_kejadian3', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('nama_ktg_kejadian3', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('kode_penyebab1', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('nama_penyebab1', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('kode_penyebab2', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('nama_penyebab2', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('kode_penyebab3', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('nama_penyebab3', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('bussines_line', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('coa_biaya', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('mata_uang', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('nilai_tukar', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('kerugian_potensial', models.FloatField(blank=True, default=None, null=True)),
                ('rra', models.FloatField(blank=True, default=None, null=True)),
                ('recovery', models.FloatField(blank=True, default=None, null=True)),
                ('kerugian_aktual', models.FloatField(blank=True, default=None, null=True)),
                ('tanggal_review', models.DateField(blank=True, default=None, null=True)),
                ('reviewer', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('hasil_review', models.TextField(blank=True, default=None, null=True)),
                ('keterangan_review', models.TextField(blank=True, default=None, null=True)),
                ('summary_kejadian', models.TextField(blank=True, default=None, null=True)),
                ('kronologi_kejadian', models.TextField(blank=True, default=None, null=True)),
                ('tindakan_unit_kerja', models.TextField(blank=True, default=None, null=True)),
                ('tindakan_perbaikan', models.TextField(blank=True, default=None, null=True)),
                ('dibuat_oleh', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('ditemukan_oleh', models.CharField(blank=True, max_length=100, null=True)),
                ('disetujui_oleh', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('dihapus', models.BooleanField(blank=True, default=False, null=True)),
                ('risiko_kredit', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
