# Generated by Django 3.2.7 on 2022-01-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledMaster', '0002_auto_20220103_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledhistoris',
            name='nama_cabang',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
