# Generated by Django 3.2.7 on 2022-01-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledMaster', '0003_alter_ledhistoris_nama_cabang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledhistoris',
            name='kode_cabang',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ledhistoris',
            name='nama_penemu',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ledhistoris',
            name='nama_produk',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ledhistoris',
            name='nama_produk2',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ledhistoris',
            name='status',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
