# Generated by Django 3.2.7 on 2022-01-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledMaster', '0004_auto_20220103_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledhistoris',
            name='laporan_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
