# Generated by Django 3.2.7 on 2022-01-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledMaster', '0005_ledhistoris_laporan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledhistoris',
            name='historis_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
