# Generated by Django 3.2.7 on 2022-01-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledMaster', '0006_ledhistoris_historis_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledhistoris',
            name='historis_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
